name: DBC language CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: npm install
    - name: make
      run: make
  
  syntax_tests:
    name: Run Syntax Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: SublimeText/syntax-test-action@v2
        with:
          build: latest
