name: DBC language CI

on:
  push:
    branches: 
      - master
      - develop
  pull_request:
    branches: [ master ]

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 13.x
          - 14.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      - run: npm install
        name: Install Dependencies
      
      - run: make
        name: Compile and Build
      
      - run: make package
        name: Build Extension
        with: 
          name: Extension Content
          path: dbc-*.vsix
  